import {chromium} from 'playwright';
import {createServer} from 'vite';
import assert from 'node:assert/strict';
import {mkdirSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
mkdirSync('test-results',{recursive:true});
execFileSync('cargo',['run','--locked','--example','fixtures'],{stdio:'pipe'});
const ff=(...args)=>execFileSync('ffmpeg',['-hide_banner','-loglevel','error',...args,'-y']);
for(const [extension,codec]of [['mp3','libmp3lame'],['flac','flac'],['wav','pcm_s16le']])ff('-f','lavfi','-i','sine=frequency=440:sample_rate=44100:duration=2','-ac','2','-c:a',codec,'test-results/tone.'+extension);
ff('-f','lavfi','-i','testsrc=size=96x64:rate=1','-frames:v','1','-pix_fmt','rgb24','-threads','1','test-results/original.tiff');
ff('-f','lavfi','-i','testsrc=size=320x180:rate=25:duration=2','-f','lavfi','-i','sine=frequency=440:sample_rate=44100:duration=2','-c:v','libvpx-vp9','-pix_fmt','yuv420p','-c:a','libopus','-shortest','test-results/native-input.webm');
const server=await createServer({server:{host:'127.0.0.1',port:5178,strictPort:true}});await server.listen();
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--autoplay-policy=no-user-gesture-required']});
const page=await browser.newPage({viewport:{width:1600,height:1000},acceptDownloads:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));
const state=()=>page.evaluate(()=>creativeStudio.inspect());
const invoke=(engine,id,params={})=>page.evaluate(({engine,id,params})=>creativeStudio.nativeCommand(engine,id,params),{engine,id,params});
const cmd=(id,params={})=>page.evaluate(({id,params})=>creativeStudio.execute(id,params),{id,params});
const frame=f=>page.evaluate(async f=>[...await creativeStudio.framePixels(f,96,64)],f);
async function fresh(){await page.locator('#new').click();await page.waitForFunction(()=>creativeStudio.inspect().project.assets.length===0);}
async function upload(path){await page.locator('#media-input').setInputFiles(path);await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Importerad'));}
async function audioPower(start=0){return page.evaluate(async start=>{const samples=await creativeStudio.audioMixer.mix(start,4096);return Math.sqrt(samples.reduce((a,x)=>a+x*x,0)/samples.length);},start);}
async function exportFile(format,path){await page.locator('#export').click();await page.locator('#export-format').selectOption(format);const download=page.waitForEvent('download',{timeout:120000});await page.locator('#export-video').click();await(await download).saveAs(path);await page.waitForFunction(()=>!document.querySelector('#export-video').disabled);await page.locator('#export-close').click();}
try{
 await page.goto('http://127.0.0.1:5178');await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Redo'));
 await upload('test-results/layers.pcraft');let s=await state();assert.equal(s.project.assets[0].source_decoder,'photo');
 const view=await page.evaluate(()=>creativeStudio.nativeView());assert.equal(view.layers.length,2,'Native original keeps editable layers');const original=await frame(0);
 await cmd('view.set',{native_target:'original:1'});await invoke('photo','edit.transform',{matrix:[1,0,0,1,15,0]});const moved=await frame(0);assert.notDeepEqual(moved,original);assert.deepEqual(await frame(1),original);await cmd('undo');assert.deepEqual(await frame(0),original);
 await cmd('view.set',{native_target:'original:0'});await page.locator('#extended-tool').selectOption('lasso');const c=await page.locator('#canvas').boundingBox();
 await page.mouse.move(c.x+c.width*.1,c.y+c.height*.1);await page.mouse.down();for(const [x,y]of [[.45,.1],[.45,.9],[.1,.9],[.1,.1]])await page.mouse.move(c.x+c.width*x,c.y+c.height*y,{steps:4});await page.mouse.up();await page.waitForFunction(()=>creativeStudio.inspect().project.workspace.photo_selection.length>0);
 await page.locator('#native-tools').click();await page.locator('#native-tools-dialog input[type=search]').fill('image.adjustments.invert');await page.locator('.native-command-list button').click();await page.locator('.native-command-form [type=submit]').click();await page.waitForFunction(()=>creativeStudio.inspect().project.photo_operations.length===1);
 const inverted=await frame(0);assert.notDeepEqual(inverted,original);assert.deepEqual(await frame(1),original);assert.equal(inverted[(50*96+70)*4],original[(50*96+70)*4],'Lasso limits actual filter pixels');
 await page.keyboard.press('Control+d');await page.waitForFunction(()=>creativeStudio.inspect().project.workspace.photo_selection.length===0);
 await cmd('seek',{frame:1});await invoke('photo','select.rect',{x:20,y:16,width:24,height:24});await invoke('photo','edit.copyMerged');await cmd('seek',{frame:2});await invoke('photo','select.deselect');await invoke('photo','edit.paste',{inPlace:true});const pasted=await frame(2);await cmd('undo');assert.deepEqual(await frame(2),original);await cmd('redo');assert.deepEqual(await frame(2),pasted);
 await cmd('view.set',{native_target:'original:0',scope:'range'});await cmd('selection.set',{clip_id:s.active_clip.id,start:3,end:8});await cmd('seek',{frame:4});await invoke('light','mask.add',{kind:'linear',start:[.2,.2],end:[.2,.8]});await invoke('light','mask.adjust',{values:{exposure:1.5,temp:20}});const masked=await frame(4);assert.notDeepEqual(masked,original);assert.deepEqual(await frame(8),original);
 const shared=await page.evaluate(()=>creativeStudio.save());for(const mode of ['photo','film','light']){await page.locator('[data-mode='+mode+']').click();assert.equal((await state()).project.workspace.playhead,4);assert.deepEqual(await frame(4),masked);}await page.waitForFunction(()=>document.querySelector('.local-mask-list button')&& !document.querySelector('#local-exposure').disabled);assert.equal(Number(await page.locator('#local-exposure').inputValue()),1.5);await page.evaluate(json=>creativeStudio.open(json),shared);assert.deepEqual(await frame(4),masked);await page.screenshot({path:'test-results/native-studio.png'});
 await page.evaluate(async()=>{const {dbRequest}=await import('/web/storage.js');await dbRequest('media','readwrite',store=>store.delete(creativeStudio.inspect().project.assets[0].id));});await page.evaluate(json=>creativeStudio.open(json).catch(e=>e.message),shared);const relink=page.waitForEvent('filechooser');await page.locator('#assets .asset').click();await(await relink).setFiles('test-results/layers.pcraft');await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('återlänkats'));assert.deepEqual(await frame(4),masked,'Special-format relink retains every edit');
 await fresh();await upload('test-results/original.tiff');s=await state();assert.equal(s.project.assets[0].source_decoder,'photo');assert.equal((await frame(0)).length,96*64*4);
 for(const ext of ['wav','mp3','flac']){await fresh();await upload('test-results/tone.'+ext);const power=await audioPower(12000);assert.ok(power>.035&&power<.2,ext+' actual resampled tone: '+power);assert.ok((await state()).project.timeline.audio_tracks[0].items.length>0);}
 await fresh();await upload('test-results/native-input.webm');
 const nativePixels=await page.evaluate(async()=>{const project=JSON.parse(await creativeStudio.save());project.project.assets[0].source_decoder='native';await creativeStudio.open(JSON.stringify(project));return [...await creativeStudio.framePixels(20,96,64)];});assert.ok(nativePixels.some(v=>v>100));
 await cmd('seek',{frame:0});await invoke('film','sequence.addTracks',{video:1,audio:1});const graphic=await invoke('film','graphics.newShape',{shape:'rectangle',position:[110,80],size:[80,70],seconds:1});await invoke('film','graphics.set',{clip:graphic.clip,props:{fill_color:'#ff0000'}});s=await state();assert.equal(s.project.timeline.video_tracks.filter(t=>t.items.length).length,2);
 const overlay=await frame(0);assert.ok(overlay[(25*96+33)*4]>180,'Actual second-track graphic');const overlayId=graphic.clip;await invoke('film','effects.setParam',{clip:overlayId,effect:'opacity',param:'opacity',value:50});await invoke('film','effects.addKeyframe',{clip:overlayId,effect:'opacity',param:'opacity'});assert.notDeepEqual(await frame(0),overlay);await invoke('film','sequence.applyVideoTransition',{clip:overlayId,effect:'cross_dissolve',frames:8,edge:'in'});
 const audioId=(await state()).project.timeline.audio_tracks[0].items[0].id;const loud=await audioPower(12000);await invoke('film','clip.audioGain',{clips:[audioId],db:-6.020599913});const soft=await audioPower(12000);assert.ok(Math.abs(soft-loud/2)<.005);
 const beforeBackup=await frame(20),movieId=(await state()).project.assets[0].id,backupDownload=page.waitForEvent('download');await page.locator('#backup').click();await(await backupDownload).saveAs('test-results/native.cstudio-backup');await fresh();await page.evaluate(async id=>{const {dbRequest}=await import('/web/storage.js');await dbRequest('media','readwrite',store=>store.delete(id));},movieId);await page.locator('#project-input').setInputFiles('test-results/native.cstudio-backup');await page.waitForFunction(()=>document.querySelector('#status').textContent==='Projektet är öppnat');assert.deepEqual(await frame(20),beforeBackup);assert.ok(Math.abs(await audioPower(12000)-soft)<.001);
 await exportFile('webm','test-results/native-processed.webm');await exportFile('mp4','test-results/native-processed.mp4');
 const expected=await page.evaluate(async()=>[...await creativeStudio.framePixels(20,320,180)]);
 for(const ext of ['webm','mp4']){const file='test-results/native-processed.'+ext,info=JSON.parse(execFileSync('ffprobe',['-v','error','-count_frames','-show_streams','-show_format','-of','json',file],{encoding:'utf8'}));assert.equal(Number(info.streams.find(s=>s.codec_type==='video').nb_read_frames),50);assert.ok(info.streams.some(s=>s.codec_type==='audio'));assert.ok(Math.abs(Number(info.format.duration)-2)<.06);const rgba=execFileSync('ffmpeg',['-v','error','-i',file,'-vf','select=eq(n\\,20)','-frames:v','1','-pix_fmt','rgba','-f','rawvideo','pipe:1'],{maxBuffer:320*180*4+1024});let diff=0;for(let i=0;i<expected.length;i++)if(i%4!==3)diff+=Math.abs(rgba[i]-expected[i]);assert.ok(diff/(320*180*3)<12,ext+' exported pixels match the rendered project');const pcm=execFileSync('ffmpeg',['-v','error','-i',file,'-vn','-ar','48000','-ac','2','-f','f32le','pipe:1'],{maxBuffer:2_000_000});let power=0;for(let i=12000*2;i<(12000+4096)*2;i++)power+=pcm.readFloatLE(i*4)**2;assert.ok(Math.abs(Math.sqrt(power/8192)-soft)<.008,ext+' exported sound retains native mixer gain');}
 assert.deepEqual(errors,[]);console.log(JSON.stringify({result:'PASS',layered_original:true,native_canvas_tools:true,scoped_filter:true,shared_history:true,local_masks:true,native_tiff:true,streamed_audio:['WAV','MP3','FLAC'],native_movie_decoder:true,multi_track_graphics:true,effects_and_keyframes:true,transitions:true,actual_gain:true,exports:['WebM','MP4'],browser_errors:errors},null,2));
}catch(e){console.log('STATUS',await page.locator('#status').textContent());await page.screenshot({path:'test-results/native-error.png'});throw e;}finally{await browser.close();await server.close();}
