import {getMedia} from './storage.js';
import {mp4Info} from './media.js';
import {decoderConfig} from './export.js';
// Compressed originals are read in ranges; only a bounded PCM window is held.
export function createAudioMixer({rpc,attachSource,getState}){
  const indexes=new Map(),windows=new Map();let context,epoch=0,scheduled=[],nextSample=0,baseTime=0,baseSample=0,pumping;
  const R=48000;
  async function index(asset){if(indexes.has(asset.id))return indexes.get(asset.id);const blob=await getMedia(asset.id);if(!blob)throw new Error('Ljudoriginalet saknas: '+asset.name);let result;
    if(/\.wav$/i.test(asset.name)||blob.type.includes('wav')){const header=new DataView(await blob.slice(0,1024*1024).arrayBuffer());let fmt,data;for(let at=12;at+8<=header.byteLength;){const name=String.fromCharCode(...new Uint8Array(header.buffer,at,4)),length=header.getUint32(at+4,true);if(name==='fmt '){fmt={format:header.getUint16(at+8,true),channels:header.getUint16(at+10,true),rate:header.getUint32(at+12,true),align:header.getUint16(at+20,true),bits:header.getUint16(at+22,true)};}if(name==='data'){data={offset:at+8,size:length};break;}at+=8+length+(length%2);}if(!fmt||!data||fmt.channels>6||![1,3].includes(fmt.format)||![16,24,32].includes(fmt.bits))throw new Error('WAV-formatet stöds inte');result={blob,wav:{...fmt,...data}};}
    else{await attachSource(asset,blob);if(!/\.(mp4|m4a|mov)$/i.test(asset.name)&&!blob.type.includes('mp4'))result={blob,native:true};else{const m=await mp4Info(blob);const info=m?.info.audioTracks[0];if(info){const track=m.parser.getTrackById(info.id),edits=info.edits||[];let config;try{config=decoderConfig(track,info);}catch{}result=config&&window.AudioDecoder&&edits.length<=1&&!edits.some(e=>e.media_time<0||e.media_rate_integer!==1)&&(await AudioDecoder.isConfigSupported(config)).supported?{blob,track,info,config}:{blob,native:true};}else result={blob};}}
    indexes.set(asset.id,result);while(indexes.size>4){const id=indexes.keys().next().value;indexes.delete(id);windows.delete(id);}return result;
  }
  async function decode(asset,start,frames,rate){const entry=await index(asset),count=entry.wav?.channels||entry.info?.audio?.channel_count||entry.config?.numberOfChannels||2,out=Array.from({length:count},()=>new Float32Array(frames));
    if(entry.native){const data=new Float32Array(await rpc('decode-audio',{asset:asset.id,start,frames,rate}));const count=data[0];if(!Number.isInteger(count)||count<1||count>6||data.length!==1+count*frames)throw new Error('Ofullständigt ljud från avkodaren');return Array.from({length:count},(_,c)=>data.subarray(1+c*frames,1+(c+1)*frames));}
    if(entry.wav){const w=entry.wav,first=Math.floor(start*w.rate/rate),sourceFrames=Math.ceil(frames*w.rate/rate)+2,bytes=new DataView(await entry.blob.slice(w.offset+first*w.align,Math.min(w.offset+w.size,w.offset+(first+sourceFrames)*w.align)).arrayBuffer());const sample=(i,ch)=>{const at=i*w.align+Math.min(ch,w.channels-1)*(w.bits/8);if(at<0||at+w.bits/8>bytes.byteLength)return 0;if(w.format===3)return bytes.getFloat32(at,true);if(w.bits===16)return bytes.getInt16(at,true)/32768;if(w.bits===32)return bytes.getInt32(at,true)/2147483648;const v=bytes.getUint8(at)|(bytes.getUint8(at+1)<<8)|(bytes.getInt8(at+2)<<16);return v/8388608;};for(let i=0;i<frames;i++){const p=(start+i)*w.rate/rate-first,j=Math.floor(p),f=p-j;for(let ch=0;ch<count;ch++)out[ch][i]=sample(j,ch)*(1-f)+sample(j+1,ch)*f;}return out;}
    if(!entry.info)return out;if(!window.AudioDecoder)throw new Error('Webbläsaren saknar ljudavkodning');const {track,info,config}=entry,edits=info.edits||[];if(edits.length>1||edits.some(e=>e.media_time<0||e.media_rate_integer!==1))throw new Error('Ljudets redigeringslista stöds inte');const mediaOffset=(edits[0]?.media_time||0)/info.timescale;let failure;
    const decoder=new AudioDecoder({error:e=>failure=e,output:pcm=>{try{const begin=pcm.timestamp/1e6-mediaOffset;for(let ch=0;ch<count;ch++){const plane=new Float32Array(pcm.numberOfFrames);pcm.copyTo(plane,{planeIndex:Math.min(ch,pcm.numberOfChannels-1),format:'f32-planar'});const first=Math.max(0,Math.ceil(begin*rate-start)),end=Math.min(frames,Math.ceil((begin+pcm.numberOfFrames/pcm.sampleRate)*rate-start));for(let i=first;i<end;i++){const pos=((start+i)/rate-begin)*pcm.sampleRate,j=Math.floor(pos),f=pos-j;out[ch][i]=(plane[j]||0)*(1-f)+(plane[j+1]??plane[j]??0)*f;}}}catch(e){failure=e;}finally{pcm.close();}}});
    try{decoder.configure(config);const from=start/rate-.1,to=(start+frames)/rate+.04,samples=track.samples;let lo=0,hi=samples.length;while(lo<hi){const mid=(lo+hi)>>1,s=samples[mid];if((s.cts+s.duration)/s.timescale-mediaOffset<from)lo=mid+1;else hi=mid;}let count=0;for(let i=lo;i<samples.length;i++){const sample=samples[i],t=sample.cts/sample.timescale-mediaOffset;if(t>to)break;const bytes=await entry.blob.slice(sample.offset,sample.offset+sample.size).arrayBuffer();decoder.decode(new EncodedAudioChunk({type:'key',timestamp:Math.round(sample.cts/sample.timescale*1e6),duration:Math.round(sample.duration/sample.timescale*1e6),data:bytes}));if(++count%24===0)while(decoder.decodeQueueSize>12)await new Promise(r=>decoder.addEventListener('dequeue',r,{once:true}));if(failure)throw failure;}await decoder.flush();if(failure)throw failure;return out;}finally{if(decoder.state!=='closed')decoder.close();}
  }
  async function read(asset,start,frames,rate){const old=windows.get(asset.id),end=start+frames;if(old&&old.rate===rate&&start>=old.start&&end<=old.start+old.frames)return old.channels.map(c=>c.subarray(start-old.start,end-old.start));
    let channels;if(old&&old.rate===rate&&start>=old.start&&start<old.start+old.frames&&end>old.start+old.frames){const cached=old.start+old.frames-start,tail=await decode(asset,old.start+old.frames,frames-cached,rate);channels=old.channels.map((c,i)=>{const out=new Float32Array(frames);out.set(c.subarray(start-old.start));out.set(tail[i],cached);return out;});}else channels=await decode(asset,start,frames,rate);
    windows.set(asset.id,{start,frames,channels,rate});return channels;
  }
  async function mix(start,frames){const s=getState(),p=s.project,rate=p.timeline.settings.sample_rate||R,nativeStart=Math.round(start*rate/R),nativeFrames=Math.max(1,Math.round(frames*rate/R)),plan=await rpc('audio-plan',{start:nativeStart,frames:nativeFrames}),parts=[],inputs=[];let offset=0;
    for(const req of plan){const asset=p.assets.find(a=>a.id===req.asset_id);if(asset?.kind==='generator')continue;const channels=await read(asset,req.start,req.frames,req.sample_rate);inputs.push({...req,offset,channels:channels.length});for(const ch of channels){parts.push(ch);offset+=ch.length;}}
    const packed=new Float32Array(offset);let at=0;for(const part of parts){packed.set(part,at);at+=part.length;}const result=new Float32Array(await rpc('mix-audio',{start:nativeStart,frames:nativeFrames,inputs,samples:packed.buffer},[packed.buffer]));if(rate===R)return result;const out=new Float32Array(frames*2);for(let ch=0;ch<2;ch++)for(let i=0;i<frames;i++){const pos=i*rate/R,j=Math.floor(pos),f=pos-j;out[ch*frames+i]=(result[ch*nativeFrames+j]||0)*(1-f)+(result[ch*nativeFrames+Math.min(j+1,nativeFrames-1)]||0)*f;}return out;
  }
  async function stop(){epoch++;for(const node of scheduled){try{node.stop();}catch{}}scheduled=[];pumping=null;}
  async function start(frame){await stop();context??=new AudioContext({sampleRate:R});await context.resume();baseSample=Math.round(frame/(getState().project.fps.num/getState().project.fps.den)*R);nextSample=baseSample;baseTime=context.currentTime+.08;const token=epoch;await pump(token);return {seconds:()=>Math.max(baseSample/R,baseSample/R+context.currentTime-baseTime)};}
  async function pump(token=epoch){if(pumping)return pumping;pumping=(async()=>{const p=getState().project,end=Math.round(getState().total_frames/(p.fps.num/p.fps.den)*R);while(token===epoch&&nextSample<end&&baseTime+(nextSample-baseSample)/R<context.currentTime+.35){const start=nextSample,n=Math.min(4096,end-start),samples=await mix(start,n);if(token!==epoch)return;const buffer=context.createBuffer(2,n,R);for(let ch=0;ch<2;ch++)buffer.copyToChannel(samples.subarray(ch*n,(ch+1)*n),ch);const node=context.createBufferSource();node.buffer=buffer;node.connect(context.destination);const when=baseTime+(start-baseSample)/R;if(when<context.currentTime-.02){baseTime=context.currentTime-(start-baseSample)/R+.02;}node.start(Math.max(context.currentTime,baseTime+(start-baseSample)/R));scheduled.push(node);if(scheduled.length>12)scheduled.shift();nextSample+=n;}})().finally(()=>{pumping=null;});return pumping;}
  return {mix,start,stop,pump,clear(){indexes.clear();windows.clear();},inspect:()=>({sources:indexes.size,windows:windows.size})};
}
