// Original FilmCraft effect definitions drive one inspector for video, audio and transitions.
export function createEffectsUI({getState,nativeCommand,rpc,status}){
 const panel=document.createElement('section');panel.className='panel-section effect-inspector';panel.innerHTML='<h3>Effektkontroller</h3><p class="effect-target"></p><div class="effect-stack"></div><div class="effect-add"><input type="search" placeholder="Sök effekt eller övergång…" aria-label="Sök effekt"><select aria-label="Effekt"><option>Laddar effekter…</option></select><button>Lägg till</button></div>';
 document.getElementById('film-panel').append(panel);let defs,loading,signature='';const run=fn=>async(...args)=>{try{await fn(...args);}catch(e){status(e.message,true);}};
 function selected(){const p=getState()?.project;if(!p)return;const chosen=p.workspace.film_state.selection,all=[...p.timeline.video_tracks,...p.timeline.audio_tracks].flatMap(t=>t.items);return all.find(c=>chosen.includes(c.id))||all.find(c=>'clip-'+c.id===getState().active_clip?.id);}
 function untag(value){if(value?.Vec2)return [value.Vec2.x,value.Vec2.y];return value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).length===1?Object.values(value)[0]:value;}
 function control(info,value,change){value=untag(value);let el;if(info.type==='bool'){el=document.createElement('input');el.type='checkbox';el.checked=!!value;el.onchange=()=>change(el.checked);}
  else if(info.type==='choice'){el=document.createElement('select');info.options.forEach((name,i)=>el.append(new Option(name,String(i))));el.value=value;el.onchange=()=>change(Number(el.value));}
  else if(['float','angle'].includes(info.type)){el=document.createElement('input');el.type='number';el.step='any';if(info.min!=null)el.min=info.min;if(info.max!=null)el.max=info.max;el.value=Number(value??0).toFixed(2);el.onchange=()=>change(Number(el.value));}
  else if(info.type==='color'){el=document.createElement('input');el.type='color';const color=Array.isArray(value)?value.slice(0,3):[1,1,1];el.value='#'+color.map(n=>Math.round(Math.max(0,Math.min(1,n))*255).toString(16).padStart(2,'0')).join('');el.onchange=()=>change(el.value);}
  else if(info.type==='text'){el=document.createElement('input');el.type='text';el.value=value||'';el.onchange=()=>change(el.value);}
  else{el=document.createElement('input');el.type='text';el.value=JSON.stringify(value);el.onchange=()=>change(JSON.parse(el.value));}el.setAttribute('aria-label',info.label);return el;
 }
 function browse(){if(!defs)return;const q=panel.querySelector('[type=search]').value.toLowerCase(),sel=panel.querySelector('.effect-add select');sel.replaceChildren();for(const d of defs.filter(d=>!['motion','opacity','volume','panner','time_remap'].includes(d.id)&&`${d.name} ${d.category.join(' ')}`.toLowerCase().includes(q)))sel.append(new Option(d.name+' · '+d.category.slice(1).join(' / '),d.id));}
 panel.querySelector('[type=search]').oninput=browse;
 panel.querySelector('.effect-add button').onclick=run(async()=>{const c=selected();if(!c)throw new Error('Välj ett klipp först');const effect=panel.querySelector('.effect-add select').value,d=defs.find(d=>d.id===effect);if(d.kind==='VideoTransition')await nativeCommand('film','sequence.applyVideoTransition',{clip:c.id,effect,frames:12});else if(d.kind==='AudioTransition')await nativeCommand('film','sequence.applyAudioTransition',{clip:c.id,effect,frames:12});else await nativeCommand('film','effects.apply',{clips:[c.id],effect});});
 async function load(){if(loading)return loading;loading=(async()=>{if(!defs){const cat=await rpc('catalog');defs=cat.film_effects;browse();}sync();})();return loading;}
 function sync(){const c=selected();if(!c){panel.querySelector('.effect-target').textContent='Välj ett bild- eller ljudklipp';return;}const s=getState();panel.querySelector('.effect-target').textContent=`Hela klippet · ${(c.duration/s.ticks_per_second).toFixed(2)} s. Klockan skapar en nyckelbild vid spelhuvudet.`;
  if(!defs){load().catch(e=>status(e.message,true));return;}const sig=JSON.stringify([c.id,c.effects]);if(sig===signature)return;signature=sig;const stack=panel.querySelector('.effect-stack');stack.replaceChildren();c.effects.forEach((fx,index)=>{const def=defs.find(d=>d.id===fx.effect);if(!def)return;const section=document.createElement('details');section.className='effect-section';section.open=['motion','opacity','volume'].includes(fx.effect);const heading=document.createElement('summary');heading.textContent=def.name;section.append(heading);if(!['motion','opacity','volume','panner','time_remap'].includes(fx.effect)){const remove=document.createElement('button');remove.textContent='Ta bort effekt';remove.onclick=run(()=>nativeCommand('film','effects.remove',{clip:c.id,index}));section.append(remove);}for(const info of def.paramInfo){const label=document.createElement('label');label.className='field effect-param';const title=document.createElement('span');title.textContent=info.label;const input=control(info,fx.params[info.id]?.value??info.default,run(value=>nativeCommand('film','effects.setParam',{clip:c.id,effect:index,param:info.id,value})));label.append(title,input);if(info.animatable){const key=document.createElement('button');key.type='button';key.textContent='◷';key.title='Nyckelbild vid aktuell tid';key.onclick=run(()=>nativeCommand('film','effects.addKeyframe',{clip:c.id,effect:index,param:info.id}));label.append(key);}section.append(label);}stack.append(section);});
 }
 return {sync,load};
}
