export function createFilmstrip({getState,command,nativeCommand,framePixels,stop,status,isPlaying}){
  const $=id=>document.getElementById(id),root=$('tracks'),scroll=$('timeline-scroll'),ruler=$('ruler');
  let scale=1,origin=0,length=0,signature='',visibleSignature='',revision=0,detail=false,anchor=null,gesture=null,token=0,generating=false,follow=false;
  const images=new Map();let queue=[];
  const run=fn=>async(...args)=>{try{await fn(...args);}catch(e){status(e.message,true);}};
  const F=()=>{const p=getState().project;return p.fps.num/p.fps.den;};
  const ticks=f=>Math.round(f*getState().frame_ticks);
  function segments(){const p=getState().project;return p.clips.map(clip=>({clip,start:clip.start,asset:p.assets.find(a=>a.id===clip.asset_id)}));}
  function position(e,segment){const x=e.clientX-root.getBoundingClientRect().left;return Math.max(0,Math.min(segment.clip.frames-1,Math.floor(origin+x/scale)-segment.start));}
  async function select(segment,local,shift=false){
    await stop();await command('view.set',{active_clip_id:segment.clip.id},false);
    if(shift&&anchor&&anchor.id===segment.clip.id)await command('selection.set',{clip_id:segment.clip.id,start:Math.min(anchor.local,local),end:Math.max(anchor.local,local)+1},false);
    else{anchor={id:segment.clip.id,local};await command('view.set',{scope:'frame'},false);}
    await command('seek',{frame:segment.start+local});
  }
  function clipDrag(c,seg,left){
    c.onpointerdown=e=>{if(e.target.closest('.clip-title,.clip-grip'))return;if(e.button!==0)return;e.preventDefault();const local=position(e,seg);gesture={seg,local,current:local,shift:e.shiftKey,x:e.clientX,element:c,moved:false};c.setPointerCapture(e.pointerId);};
    c.onpointermove=e=>{if(!gesture||gesture.element!==c)return;gesture.current=position(e,seg);if(Math.abs(e.clientX-gesture.x)>4){gesture.moved=true;let over=c.querySelector('.drag-range');if(!over){over=document.createElement('div');over.className='range-overlay drag-range';c.append(over);}over.style.left=((Math.min(gesture.local,gesture.current)+seg.start-left)*scale)+'px';over.style.width=((Math.abs(gesture.local-gesture.current)+1)*scale)+'px';}};
    c.onpointerup=run(async()=>{const g=gesture;gesture=null;if(!g)return;c.querySelector('.drag-range')?.remove();if(g.moved){await stop();anchor={id:seg.clip.id,local:g.local};await command('view.set',{active_clip_id:seg.clip.id},false);await command('selection.set',{clip_id:seg.clip.id,start:Math.min(g.local,g.current),end:Math.max(g.local,g.current)+1},false);await command('seek',{frame:seg.start+g.current});}else await select(seg,g.current,g.shift);refresh();});
    c.onpointercancel=()=>{gesture=null;c.querySelector('.drag-range')?.remove();};
    c.ondblclick=run(()=>command('view.set',{active_clip_id:seg.clip.id,scope:'clip'},false));
    c.onkeydown=run(async e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();await select(seg,Math.max(0,left-seg.start),e.shiftKey);}});c.tabIndex=0;
    for(const edge of ['in','out']){const grip=document.createElement('span');grip.className='clip-grip '+edge;grip.title='Dra för att trimma · Shift: flytta följande klipp';c.append(grip);grip.onpointerdown=e=>{e.stopPropagation();e.preventDefault();const x=e.clientX;let delta=0;grip.setPointerCapture(e.pointerId);grip.onpointermove=ev=>{delta=Math.round((ev.clientX-x)/scale);c.style.opacity='.65';c.title=`Trimma ${delta>0?'+':''}${delta} bildrutor`;};grip.onpointerup=run(async ev=>{ev.stopPropagation();grip.onpointermove=null;c.style.opacity='';if(delta)await nativeCommand('film','timeline.trim',{clip:Number(seg.clip.id.slice(5)),edge,mode:ev.shiftKey?'ripple':'regular',deltaFrames:delta});});};}
  }
  function trackDrop(row,track){
    row.ondragover=e=>{if(e.dataTransfer.types.includes('text/studio-clip')){e.preventDefault();row.classList.add('drop-target');}};row.ondragleave=()=>row.classList.remove('drop-target');
    row.ondrop=run(async e=>{e.preventDefault();row.classList.remove('drop-target');const id=e.dataTransfer.getData('text/studio-clip');if(!id)return;const at=Math.max(0,Math.floor(origin+(e.clientX-root.getBoundingClientRect().left)/scale));await stop();await nativeCommand('film','timeline.move',{moves:[{clip:Number(id.slice(5)),track:track.id,time:ticks(at)}],insert:!!e.shiftKey,linked:true});});
  }
  function refresh(){
    const s=getState();if(!s)return;const seq=s.project.timeline,video=seq?.video_tracks||[],audio=detail?seq?.audio_tracks||[]:[];
    const fit=Math.max(1,scroll.clientWidth-34)/Math.max(1,s.total_frames),zoom=Number($('timeline-zoom').value)/100;scale=fit*Math.pow(Math.max(1,76/fit),zoom);
    const maxFrames=Math.max(1,Math.floor(4_000_000/scale));origin=s.total_frames>maxFrames?Math.max(0,Math.min(s.total_frames-maxFrames,s.project.workspace.playhead-Math.floor(maxFrames/2))):0;length=Math.min(Math.max(1,s.total_frames),maxFrames);
    const sig=JSON.stringify([seq,s.project.clips,s.project.layers,s.project.adjustments,s.project.photo_operations,s.project.project_look,revision,zoom,scroll.clientWidth,origin,detail]);
    if(sig!==signature){signature=sig;visibleSignature='';token++;queue=[];root.replaceChildren();ruler.replaceChildren();$('operation-tracks').replaceChildren();const width=Math.max(scroll.clientWidth-34,length*scale);for(const el of [root,ruler,$('operation-tracks')])el.style.width=width+'px';root.classList.toggle('frame-view',scale>=65);
      let y=0;const rows=new Map();for(const t of [...video].reverse()){
        const row=document.createElement('div');row.className='timeline-track video-track'+(!t.enabled?' disabled-track':'');row.dataset.trackId=t.id;row.style.top=y+'px';row.style.height='94px';row.style.width=width+'px';const label=document.createElement('span');label.className='track-label';label.textContent=t.name;label.title='Dra klippets rubrik hit för att flytta till spåret';row.append(label);trackDrop(row,t);root.append(row);rows.set(t.id,y);y+=96;
      }
      for(const seg of segments()){
        const left=Math.max(origin,seg.start),end=Math.min(origin+length,seg.start+seg.clip.frames);if(left>=end)continue;const c=document.createElement('div');c.className='clip';c.dataset.clipId=seg.clip.id;c.setAttribute('role','group');c.setAttribute('aria-label',seg.asset?.name||'Klipp');c.style.top=(rows.get(seg.clip.track)||0)+'px';c.style.left=((left-origin)*scale)+'px';c.style.width=((end-left)*scale)+'px';
        const title=document.createElement('div');title.className='clip-title';title.draggable=true;title.title='Dra till en tidsposition eller ett spår · Shift infogar';title.ondragstart=e=>{e.dataTransfer.setData('text/studio-clip',seg.clip.id);e.dataTransfer.effectAllowed='move';};title.textContent=`${seg.asset?.name||'Klipp'} · ${(seg.clip.frames/F()).toFixed(2)} s`;const cells=document.createElement('div');cells.className='frame-cells';c.append(title,cells);root.append(c);clipDrag(c,seg,left);trackDrop(c,video.find(t=>t.id===seg.clip.track)||{id:seg.clip.track});
      }
      for(const t of video){const top=rows.get(t.id);for(const x of t.transitions||[]){const start=Math.round((x.start||0)/s.frame_ticks),end=start+Math.round((x.duration||0)/s.frame_ticks);if(end<=origin||start>=origin+length)continue;const el=document.createElement('button');el.className='timeline-transition';el.style.left=((Math.max(start,origin)-origin)*scale)+'px';el.style.top=(top+25)+'px';el.style.width=(Math.max(1,Math.min(end,origin+length)-Math.max(start,origin))*scale)+'px';el.textContent=x.effect?.name||x.effect?.id||'Övergång';el.title='Redigera övergången';el.onclick=run(()=>{selectTransition(x);});root.append(el);}}
      for(const t of audio){const row=document.createElement('div');row.className='timeline-track audio-track'+(t.muted||!t.enabled?' disabled-track':'');row.style.top=y+'px';row.style.height='42px';row.style.width=width+'px';const label=document.createElement('span');label.className='track-label';label.textContent=t.name;row.append(label);trackDrop(row,t);root.append(row);
        for(const c of t.items){const start=Math.round(c.start/s.frame_ticks),frames=Math.round(c.duration/s.frame_ticks);if(start+frames<=origin||start>=origin+length)continue;const a=document.createElement('div');a.className='operation audio-operation'+(!c.enabled?' disabled-track':'');a.style.left=((start-origin)*scale)+'px';a.style.top=(y+6)+'px';a.style.width=(frames*scale)+'px';const asset=s.project.assets.find(a=>a.native_item?.id===c.item||Number(a.id.replace('resource-',''))===c.item);a.textContent=`${asset?.name||c.name||'Ljud'} · ${c.gain_db.toFixed(1)} dB`;a.draggable=true;a.ondragstart=e=>{e.dataTransfer.setData('text/studio-clip','clip-'+c.id);};a.onclick=run(()=>nativeCommand('film','timeline.select',{clips:[c.id],add:false,toggle:false}));trackDrop(a,t);root.append(a);}y+=44;
      }
      root.style.height=Math.max(92,y)+'px';const step=Math.max(1,Math.ceil(90/scale));ruler.dataset.step=step;ruler.dataset.fps=F();if(detail)renderOperations(s);renderVisible();
    }
    for(const el of root.querySelectorAll('.playhead,.range-overlay:not(.drag-range),.edit-marker'))el.remove();
    const playhead=document.createElement('div');playhead.className='playhead';playhead.style.left=((s.project.workspace.playhead-origin)*scale)+'px';root.append(playhead);
    for(const seg of segments()){const c=[...root.children].find(el=>el.dataset.clipId===seg.clip.id);if(!c)continue;const left=Math.max(origin,seg.start);c.classList.toggle('active',s.active_clip?.id===seg.clip.id);const range=s.project.workspace.selection;
      if(range?.clip_id===seg.clip.id&&s.project.workspace.scope==='range'){const p=document.createElement('div');p.className='range-overlay';p.style.left=((seg.start+range.start-left)*scale)+'px';p.style.width=((range.end-range.start)*scale)+'px';c.append(p);}
      for(const edit of [...s.project.adjustments,...(s.project.photo_operations||[])].filter(a=>a.scope.clip_id===seg.clip.id)){const p=document.createElement('div');p.className='edit-marker';p.title=edit.call?'PhotoCraft · '+edit.call.command:'LightCraft-justering';p.style.left=((seg.start+edit.scope.start-left)*scale)+'px';p.style.width=((edit.scope.end-edit.scope.start)*scale)+'px';if(edit.call)p.style.background='#bc9adb';c.append(p);}
    }
    if(follow){const x=(s.project.workspace.playhead-origin)*scale;if(x<scroll.scrollLeft||x>scroll.scrollLeft+scroll.clientWidth-100)scroll.scrollLeft=Math.max(0,x-scroll.clientWidth/3);follow=false;}renderVisible();
  }
  async function selectTransition(x){const frames=Math.round(x.duration/getState().frame_ticks);await nativeCommand('film','timeline.select',{clips:[x.to||x.from],add:false,toggle:false});status(`Övergång · ${frames} bildrutor. Öppna FilmCrafts övergångsverktyg för parametrar.`);}
  function renderOperations(s){const tracks=$('operation-tracks');let row=0;for(const layer of s.project.layers){const seg=segments().find(x=>x.clip.id===layer.scope.clip_id);if(!seg)continue;const item=document.createElement('div');item.className='operation layer-operation';item.dataset.layerId=layer.id;item.style.left=((seg.start+layer.scope.start-origin)*scale)+'px';item.style.width=((layer.scope.end-layer.scope.start)*scale)+'px';item.style.top=(row++*30)+'px';item.textContent=layer.name;item.title=`${layer.name} · bildruta ${layer.scope.start}–${layer.scope.end-1}`;item.onclick=run(()=>command('view.set',{selected_layer:layer.id},false));
      for(const edge of ['start','end']){const grip=document.createElement('span');grip.className='layer-grip '+edge;grip.title='Dra för att ändra lagrets tidsintervall';item.append(grip);grip.onpointerdown=e=>{e.stopPropagation();const x=e.clientX,old=layer.scope[edge];grip.setPointerCapture(e.pointerId);let next=old;grip.onpointermove=ev=>{const local=Math.round(old+(ev.clientX-x)/scale);next=edge==='start'?Math.max(0,Math.min(layer.scope.end-1,local)):Math.max(layer.scope.start+1,Math.min(seg.clip.frames,local));item.style.left=((seg.start+(edge==='start'?next:layer.scope.start)-origin)*scale)+'px';item.style.width=(((edge==='end'?next:layer.scope.end)-(edge==='start'?next:layer.scope.start))*scale)+'px';};grip.onpointerup=run(async ev=>{ev.stopPropagation();grip.onpointermove=null;await command('layer.scope',{id:layer.id,start:edge==='start'?next:layer.scope.start,end:edge==='end'?next:layer.scope.end});});};}tracks.append(item);}tracks.style.height=(row*30)+'px';}
  function renderVisible(){const s=getState();if(!s)return;const first=Math.max(origin,Math.floor(scroll.scrollLeft/scale)+origin),last=Math.min(origin+length,Math.ceil((scroll.scrollLeft+scroll.clientWidth)/scale)+origin),step=scale>=65?1:Math.max(1,Math.ceil(76/scale));const visible=`${token}:${first}:${last}:${step}`;if(visible===visibleSignature){drain();return;}visibleSignature=visible;queue=[];
    for(const seg of segments()){const c=[...root.children].find(el=>el.dataset.clipId===seg.clip.id);if(!c)continue;const cells=c.querySelector('.frame-cells');cells.replaceChildren();const left=Math.max(origin,seg.start),begin=Math.max(0,Math.floor((first-seg.start)/step)*step),end=Math.min(seg.clip.frames,last-seg.start+step);
      for(let local=begin;local<end;local+=step){if(local+seg.start<origin)continue;const cell=document.createElement('div');cell.className='frame-cell';cell.dataset.frame=local;cell.style.left=((seg.start+local-left)*scale)+'px';cell.style.width=(Math.min(step,seg.clip.frames-local)*scale)+'px';const img=document.createElement('img');img.alt='';const label=document.createElement('span');label.textContent=scale>=65?String(local):`${(local/F()).toFixed(1)} s`;cell.append(img,label);cells.append(cell);const key=`${revision}:${seg.clip.id}:${seg.clip.source_in}:${seg.clip.speed}:${local}`;if(images.has(key))img.src=images.get(key);else if(!isPlaying())queue.push({key,img,seg,local,global:seg.start+local,token});}}
    ruler.replaceChildren();const stepR=Number(ruler.dataset.step)||1;for(let frame=Math.floor(first/stepR)*stepR;frame<last+stepR;frame+=stepR){const b=document.createElement('button');b.className='ruler-tick';b.style.left=((frame-origin)*scale)+'px';b.textContent=scale>=65?String(frame):`${(frame/F()).toFixed(1)}s`;b.onclick=run(()=>command('seek',{frame:Math.min(s.total_frames-1,Math.max(0,frame))}));ruler.append(b);}drain();
  }
  async function drain(){if(generating)return;generating=true;try{while(queue.length&&!isPlaying()){const job=queue.shift();if(job.token!==token||!job.img.isConnected)continue;try{const pixels=await framePixels(job.global,112,63,false,job.seg.clip.id);if(job.token!==token)continue;const c=document.createElement('canvas');c.width=112;c.height=63;c.getContext('2d').putImageData(new ImageData(new Uint8ClampedArray(pixels),112,63),0,0);const url=c.toDataURL('image/jpeg',.75);images.set(job.key,url);while(images.size>128)images.delete(images.keys().next().value);if(job.img.isConnected)job.img.src=url;}catch{/* Canvas reports missing original media. */}}}finally{generating=false;}}
  scroll.addEventListener('scroll',()=>requestAnimationFrame(renderVisible));$('timeline-zoom').oninput=()=>{signature='';follow=true;refresh();};$('timeline-fit').onclick=()=>{$('timeline-zoom').value=0;signature='';scroll.scrollLeft=0;refresh();};$('timeline-frame').onclick=()=>{$('timeline-zoom').value=100;signature='';follow=true;refresh();};$('timeline-detail').onclick=()=>{detail=!detail;$('timeline-detail').setAttribute('aria-pressed',String(detail));signature='';refresh();};new ResizeObserver(()=>refresh()).observe(scroll);
  return {refresh,invalidate(){revision++;images.clear();signature='';},reset(){token++;queue=[];images.clear();anchor=null;signature='';},follow(){follow=true;},inspect:()=>({scale,origin,thumbnails:images.size,decoders:0})};
}
