import {icon} from './icons.js';

// These inspectors dispatch the original object engines. Only Studio's worker
// holds saved state; these views and gesture previews can always be discarded.
export function createGraphicsUI({getState,nativeCommand,rpc,command,editScope,canvasCoordinates,status,canvas,overlay,openTools}) {
  const $=id=>document.getElementById(id), views={}, panels={}, run=fn=>async(...args)=>{try{await fn(...args);}catch(e){status(e.message,true);}};
  let gesture,signature='',token=0;
  const selected=(engine)=>{const v=views[engine];return Array.isArray(v?.selection)?v.selection:v?.selection?.items||[];};
  function objects(engine){const v=views[engine];return engine==='vector'?v?.layers||[]:(v?.spreads||[]).flatMap(s=>s.items||[]);}
  function flatten(nodes){return nodes.flatMap(n=>[n,...flatten(n.children||[])]);}
  function bounds(engine,node){const b=node?.bounds;if(!b)return null;return Array.isArray(b)?[b[0],b[1],b[2]-b[0],b[3]-b[1]]:[b.x,b.y,b.width,b.height];}
  async function select(engine,ids){const scope=getState().project.graphic_layers.find(l=>l.id===views[engine]?.studio_layer)?.scope;await nativeCommand(engine,engine==='vector'?'select.set':'selection.set',{ids},scope);}
  for(const engine of ['vector','design']) {
    const panel=$(engine+'-panel');panels[engine]=panel;
    panel.innerHTML=`<section class="panel-section graphic-properties"><h3>${engine==='vector'?'Vektorobjekt':'Sidlayout'}</h3><p class="graphic-scope"></p><label class="field">Grafiklager <select aria-label="${engine==='vector'?'Vektor':'Layout'}lager"></select></label><div class="graphic-actions"><button data-action="new">Nytt lager</button><button data-action="scope">Välj lagrets intervall</button></div><h4>Transformation</h4><div class="graphic-transform"><label>X <input name="x" type="number" step="1"></label><label>Y <input name="y" type="number" step="1"></label><label>Bredd <input name="width" type="number" min="1" step="1"></label><label>Höjd <input name="height" type="number" min="1" step="1"></label></div><button class="full-button" data-action="transform">Använd transformation</button><h4>${engine==='vector'?'Utseende':'Ram och text'}</h4><div class="graphic-appearance"></div><div class="graphic-actions"><button data-action="duplicate">Duplicera</button><button data-action="group">Gruppera</button><button data-action="ungroup">Dela upp</button></div><h4>Objekt</h4><div class="graphic-object-list"></div><button class="full-button" data-action="all">Alla ${engine==='vector'?'vektor':'layout'}verktyg…</button></section>`;
    const appearance=panel.querySelector('.graphic-appearance');
    if(engine==='vector')appearance.innerHTML='<label class="field">Fyllning <input type="color" data-fill value="#e84ecb"></label><label class="field">Linje <input type="color" data-stroke value="#ffffff"></label><label class="field">Linjebredd <input type="number" data-weight min="0" value="1"></label><label class="field">Opacitet <input type="range" data-opacity min="0" max="100" value="100"></label><label class="field">Text <input data-text value="Creative Studio"></label><label class="field">Textstorlek <input type="number" data-size min="1" value="48"></label>';
    else appearance.innerHTML='<label class="field">Fyllning <select data-fill><option>[Black]</option><option>[Paper]</option><option>[None]</option></select></label><label class="field">Text <textarea data-text rows="3">Din text här</textarea></label><label class="field">Kolumner <input type="number" data-columns min="1" max="20" value="1"></label><label class="field">Spaltmellanrum <input type="number" data-gutter min="0" value="12"></label><label class="field">Indrag <input type="number" data-inset min="0" value="0"></label><button class="full-button" data-action="text-options">Använd textram</button>';
    const apply=(id,params)=>nativeCommand(engine,id,{...params,ids:selected(engine)});
    panel.querySelector('select').onchange=run(()=>command('view.set',{graphic_target:panel.querySelector('select').value||null},false));
    panel.querySelector('[data-action=new]').onclick=run(()=>command('view.set',{graphic_target:null},false));
    panel.querySelector('[data-action=scope]').onclick=run(async()=>{const p=getState().project,l=p.graphic_layers.find(l=>l.id===views[engine]?.studio_layer);if(!l)return;const clip=p.clips.find(c=>c.id===l.scope.clip_id);if(!clip)return;const start=(p.timeline?clip.start:p.clips.slice(0,p.clips.indexOf(clip)).reduce((n,c)=>n+c.frames,0))+l.scope.start;await command('view.set',{scope:'range',playhead:start,selection:{...l.scope}},false);});
    panel.querySelector('[data-action=transform]').onclick=run(async()=>{const node=flatten(objects(engine)).find(o=>selected(engine).includes(o.id)),b=bounds(engine,node);if(!b)throw new Error('Välj ett objekt på canvasen eller i objektlistan.');const vals=['x','y','width','height'].map(n=>Number(panel.querySelector(`[name=${n}]`).value));if(!vals.every(Number.isFinite)||vals[2]<=0||vals[3]<=0)throw new Error('Ange en giltig storlek.');const [x,y,w,h]=vals;if(engine==='vector')await apply('object.transform',{matrix:[w/Math.max(.001,b[2]),0,0,h/Math.max(.001,b[3]),x-b[0]*w/Math.max(.001,b[2]),y-b[1]*h/Math.max(.001,b[3])]});else await apply('transform.resize',{from:[b[0],b[1],b[0]+b[2],b[1]+b[3]],to:[x,y,x+w,y+h]});});
    for(const action of ['duplicate','group','ungroup'])panel.querySelector(`[data-action=${action}]`).onclick=run(()=>apply(action==='duplicate'?'edit.duplicate':'object.'+action,{}));
    panel.querySelector('[data-action=all]').onclick=()=>openTools(engine,'');
    panel.querySelector('[data-fill]').onchange=run(()=>apply(engine==='vector'?'paint.setFill':'object.fill',engine==='vector'?{color:panel.querySelector('[data-fill]').value}:{swatch:panel.querySelector('[data-fill]').value}));
    if(engine==='vector') {
      panel.querySelector('[data-stroke]').onchange=run(()=>apply('paint.setStroke',{color:panel.querySelector('[data-stroke]').value}));panel.querySelector('[data-weight]').onchange=run(()=>apply('stroke.set',{weight:Number(panel.querySelector('[data-weight]').value)}));
      panel.querySelector('[data-opacity]').onchange=run(()=>apply('object.setProps',{opacity:Number(panel.querySelector('[data-opacity]').value)}));
    }else panel.querySelector('[data-action=text-options]').onclick=run(()=>apply('object.textFrameOptions',{columns:Number(panel.querySelector('[data-columns]').value),gutter:Number(panel.querySelector('[data-gutter]').value),inset:Number(panel.querySelector('[data-inset]').value)}));
  }
  async function refresh(engine){const t=++token,p=getState().project,v=await rpc('graphics-view',{engine});if(t!==token||getState().project!==p)return;views[engine]=v;const panel=panels[engine],list=panel.querySelector('.graphic-object-list'),layers=panel.querySelector('select');layers.replaceChildren(new Option('Nytt grafiklager',''));for(const l of p.graphic_layers.filter(l=>l.engine===engine))layers.add(new Option(`${l.id} · ${l.scope.start+1}–${l.scope.end}`,l.id));layers.value=v.studio_layer||'';panel.querySelector('.graphic-scope').textContent=$('scope-description').textContent;const chosen=selected(engine);list.replaceChildren();for(const obj of flatten(objects(engine))){const b=document.createElement('button');b.className='graphic-object'+(chosen.includes(obj.id)?' active':'');b.innerHTML=icon(obj.kind?.toLowerCase().includes('text')?'type':'square');const text=document.createElement('span');text.textContent=obj.name||obj.kind||'Objekt';b.append(text);b.onclick=run(e=>select(engine,e.shiftKey?[...new Set([...chosen,obj.id])]:[obj.id]));list.append(b);}const node=flatten(objects(engine)).find(o=>chosen.includes(o.id)),rect=bounds(engine,node);for(const [i,n]of ['x','y','width','height'].entries()){const input=panel.querySelector(`[name=${n}]`);if(document.activeElement!==input)input.value=rect?Math.round(rect[i]*100)/100:'';input.disabled=!rect;}for(const action of ['transform','duplicate','group','ungroup','text-options']){const b=panel.querySelector(`[data-action=${action}]`);if(b)b.disabled=!chosen.length;}if(engine==='design'&&v.swatches){const input=panel.querySelector('[data-fill]'),value=input.value;input.replaceChildren(...v.swatches.map(s=>new Option(typeof s==='string'?s:s.name||s.id,typeof s==='string'?s:s.name||s.id)));if([...input.options].some(o=>o.value===value))input.value=value;}}
  async function coordinates(points){const p=getState().project;return (await canvasCoordinates(points,'source')).map(pt=>[pt[0]*p.width,pt[1]*p.height]);}
  async function start(tool,point,e){const [,engine,id]=tool.split(':');if(!getState().active_clip)throw new Error('Importera media innan du lägger till grafik.');const scope=editScope();if(getState().project.workspace.scope==='project')throw new Error('Välj bildruta, intervall eller klipp för grafik.');if(id==='select'){await refresh(engine);const [pos]=await coordinates([point]);const obj=flatten(objects(engine)).reverse().find(o=>{const b=bounds(engine,o);return b&&pos[0]>=b[0]&&pos[1]>=b[1]&&pos[0]<=b[0]+b[2]&&pos[1]<=b[1]+b[3];});if(obj)await select(engine,[obj.id]);else status('Välj ett grafiklager i egenskapspanelen för att redigera dess objekt.');return;}gesture={engine,id,scope,points:[point]};canvas.setPointerCapture(e.pointerId);}
  function move(point){if(!gesture)return;if(gesture.points.length<20000)gesture.points.push(point);const c=$('stroke-preview'),a=gesture.points[0];overlay.clearRect(0,0,c.width,c.height);overlay.strokeStyle='white';overlay.lineWidth=1;overlay.setLineDash([4,3]);overlay.strokeRect(a[0]*c.width,a[1]*c.height,(point[0]-a[0])*c.width,(point[1]-a[1])*c.height);overlay.setLineDash([]);}
  async function end(){const g=gesture;cancel();if(!g)return;const pts=await coordinates(g.points),a=pts[0],b=pts.at(-1),x=Math.min(a[0],b[0]),y=Math.min(a[1],b[1]),width=Math.max(1,Math.abs(b[0]-a[0])),height=Math.max(1,Math.abs(b[1]-a[1])),panel=panels[g.engine];let id=g.id,params={x,y,width,height};if(g.engine==='vector'){if(id==='shape.line')params={x1:a[0],y1:a[1],x2:b[0],y2:b[1]};if(['shape.polygon','shape.star'].includes(id))params={cx:x+width/2,cy:y+height/2,radius:Math.max(width,height)/2,radius1:Math.max(width,height)/2,radius2:Math.max(width,height)/4,sides:6,points:5};if(id==='path.create')params={anchors:pts.map(([x,y])=>({x,y})),closed:false};if(id==='text.create')params={x:a[0],y:a[1],text:panel.querySelector('[data-text]').value,size:Number(panel.querySelector('[data-size]').value)};const layer=getState().project.graphic_layers.find(l=>l.id===getState().project.workspace.graphic_target);if(layer&&JSON.stringify(layer.scope)!==JSON.stringify(g.scope))await command('view.set',{graphic_target:null},false);await nativeCommand('vector','select.set',{ids:[]},g.scope);await nativeCommand('vector','paint.setFill',{color:panel.querySelector('[data-fill]').value},g.scope);}else{if(id==='line.create')params={a,b};else{params={rect:[x,y,x+width,y+height],shape:id.endsWith('ellipse')?'ellipse':'rectangle',content:id.endsWith('text')?'text':'graphic',caret:false};if(id.endsWith('text'))params.text=panel.querySelector('[data-text]').value;id='frame.create';}}await nativeCommand(g.engine,id,params,g.scope);status('Grafik skapad · '+$('scope-description').textContent);}
  function cancel(){gesture=null;const c=$('stroke-preview');overlay.clearRect(0,0,c.width,c.height);}
  return {start,move,end,cancel,sync(){const p=getState()?.project;if(!p)return;const engine=p.workspace.mode;if(!['vector','design'].includes(engine))return;const sig=JSON.stringify([engine,p.graphic_layers,p.workspace.graphic_target,p.workspace.playhead,p.workspace.scope,p.workspace.selection]);if(sig!==signature){signature=sig;refresh(engine).catch(e=>status(e.message,true));}},inspect:engine=>structuredClone(views[engine])};
}
