import {createEffectsUI} from './effects-ui.js';
// One command surface over the same worker-owned project. Canvas tools and menus
// dispatch the original engines; the UI never owns a second document.
export function createNativeUI({getState,nativeCommand,nativeView,canvasCoordinates,rpc,command,selectTool,status,editScope,isPlaying,overlay,canvas}){
  const effectsUI=createEffectsUI({getState,nativeCommand,rpc,status});
  const $=id=>document.getElementById(id),run=fn=>async(...args)=>{try{await fn(...args);}catch(e){status(e.message,true);}};
  const tools={lasso:['Lasso','photo','select.lasso'],wand:['Trollstav','photo','select.magicWand'],gradient:['Övertoning','photo','paint.gradient'],bucket:['Färgpyts','photo','paint.bucket'],clone:['Klonstämpel · Alt-klick för källa','photo','paint.cloneStamp'],heal:['Läkningspensel · Alt-klick för källa','photo','paint.healingBrush'],spotHeal:['Punktlagning','photo','paint.spotHealing'],pencil:['Penna','photo','paint.pencil'],mixer:['Blandarpensel','photo','paint.mixerBrush'],replaceColor:['Färgersättning','photo','paint.colorReplacement'],backgroundErase:['Bakgrundssudd','photo','paint.backgroundEraser'],magicErase:['Magiskt sudd','photo','paint.magicEraser'],dodge:['Skugga · ljusa upp','photo','paint.dodge'],burn:['Efterbelys · mörka ned','photo','paint.burn'],sponge:['Svamp','photo','paint.sponge'],blur:['Oskärpeverktyg','photo','paint.blur'],sharpen:['Skärpeverktyg','photo','paint.sharpen'],smudge:['Smeta','photo','paint.smudge'],rectangle:['Rektangel','photo','shape.create'],ellipse:['Ellips','photo','shape.create'],line:['Linje','photo','shape.create'],pen:['Fri vektorform','photo','shape.create'],maskLinear:['Linjär framkallningsmask','light','mask.add'],maskRadial:['Radiell framkallningsmask','light','mask.add'],maskBrush:['Lokal justeringspensel','light','mask.brushStroke'],remove:['Ta bort / laga','light','spot.add'],redEye:['Röda ögon','light','redeye.add'],crop:['Beskärning','light','crop.set']};
  let catalog,engine='photo',selected,gesture,cloneSource,layerToken=0,viewSignature='',currentView,maskTarget;
  const dialog=document.createElement('dialog');dialog.id='native-tools-dialog';dialog.innerHTML='<div class="dialog-heading"><h2>Alla verktyg</h2><button aria-label="Stäng">×</button></div><div class="native-catalog-toolbar"><select aria-label="Verktygsområde"><option value="photo">PhotoCraft</option><option value="light">LightCraft</option><option value="film">FilmCraft</option></select><input type="search" placeholder="Sök verktyg, filter eller effekt…" aria-label="Sök verktyg"><select class="native-category" aria-label="Kategori"><option value="">Alla kategorier</option></select></div><div class="native-catalog-body"><div class="native-command-list"></div><form class="native-command-form"><h3>Välj ett verktyg</h3><p class="native-command-scope"></p><div class="native-param-fields"></div><p class="native-command-note"></p><button class="primary full-button" type="submit" disabled>Använd på vald omfattning</button></form></div>';
  document.body.append(dialog);dialog.querySelector('.dialog-heading button').onclick=()=>dialog.close();
  const area=dialog.querySelector('.native-catalog-toolbar select'),search=dialog.querySelector('input[type=search]'),category=dialog.querySelector('.native-category'),list=dialog.querySelector('.native-command-list'),form=dialog.querySelector('form'),fields=dialog.querySelector('.native-param-fields'),apply=form.querySelector('[type=submit]');
  const browse=document.createElement('button');browse.id='native-tools';browse.textContent='Alla verktyg';browse.title='Originalens verktyg, filter och effekter (Ctrl+K)';browse.onclick=()=>open(getState()?.project.workspace.mode||'photo');$('tools').append(browse);
  const toolSelect=document.createElement('select');toolSelect.id='extended-tool';toolSelect.setAttribute('aria-label','Fler canvasverktyg');toolSelect.append(new Option('Fler canvasverktyg…',''));for(const [id,[label]]of Object.entries(tools))toolSelect.append(new Option(label,id));toolSelect.onchange=()=>{if(toolSelect.value)selectTool('native:'+toolSelect.value);};$('tools').append(toolSelect);
  const filterMenu=document.createElement('details');filterMenu.className='app-menu';filterMenu.innerHTML='<summary>Filter</summary><div class="app-menu-content"></div>';for(const [name,q]of [['Alla filter…',''],['Oskärpa…','blur'],['Skärpa…','sharpen'],['Förvrängning…','distort'],['Brus…','noise'],['Rendering…','render']]){const b=document.createElement('button');b.textContent=name;b.onclick=()=>{filterMenu.open=false;open('photo',q,'Filter');};filterMenu.lastChild.append(b);}$('app-menus').insertBefore(filterMenu,$('app-menus').children[5]);
  const nativeLayers=document.createElement('section');nativeLayers.className='panel-section native-layer-section';nativeLayers.innerHTML='<h3>Objekt och lager</h3><div class="native-layer-list"></div><button class="full-button">Egenskaper och lagerverktyg…</button>';$('photo-panel').append(nativeLayers);nativeLayers.lastChild.onclick=()=>open('photo','','Layer');
  const masks=document.createElement('section');masks.className='panel-section native-mask-section';masks.innerHTML='<h3>Lokala justeringar</h3><div class="local-mask-buttons"></div><div class="local-mask-list"></div><label class="field">Lokal exponering <input id="local-exposure" type="range" min="-5" max="5" step="0.05" value="0"><output>0</output></label><button class="full-button">Masker, ta bort och beskärning…</button>';$('light-panel').append(masks);for(const [id,label]of [['maskBrush','Pensel'],['maskLinear','Linjär'],['maskRadial','Radiell'],['remove','Laga'],['crop','Beskär']]){const b=document.createElement('button');b.textContent=label;b.onclick=()=>selectTool('native:'+id);masks.querySelector('.local-mask-buttons').append(b);}masks.lastChild.onclick=()=>open('light');const localMore=document.createElement('details');localMore.className='develop-section';localMore.innerHTML='<summary>Alla lokala reglage</summary>';
  const localSpecs=[['temp','Temperatur',-100,100],['tint','Färgton',-100,100],['contrast','Kontrast',-100,100],['highlights','Högdagrar',-100,100],['shadows','Skuggor',-100,100],['whites','Vita',-100,100],['blacks','Svarta',-100,100],['texture','Textur',-100,100],['clarity','Klarhet',-100,100],['dehaze','Ta bort dis',-100,100],['hue','Nyans',-180,180],['saturation','Mättnad',-100,100],['sharpness','Skärpa',-100,100],['noise','Brus',0,100],['moire','Moiré',-100,100],['defringe','Kantfärg',0,100],['color_hue','Färgöverlägg · nyans',0,360],['color_sat','Färgöverlägg · mättnad',0,100],['amount','Maskens styrka',0,200]];
  for(const [key,label,min,max] of localSpecs){const row=document.createElement('label');row.className='field';const name=document.createElement('span');name.textContent=label;const input=document.createElement('input');input.type='range';input.min=min;input.max=max;input.step=1;input.dataset.local=key;input.setAttribute('aria-label','Lokal '+label);const value=document.createElement('output');input.oninput=()=>value.textContent=input.value;input.onchange=run(()=>nativeCommand('light','mask.adjust',{values:{[key]:Number(input.value)}}));row.append(name,input,value);localMore.append(row);}masks.insertBefore(localMore,masks.lastChild);
  const maskActions=document.createElement('div');maskActions.className='local-mask-buttons';for(const [label,id]of [['Invertera','mask.invert'],['Duplicera','mask.duplicate'],['Visa/dölj','mask.visible'],['Ta bort','mask.delete']]){const b=document.createElement('button');b.textContent=label;b.dataset.maskAction='true';b.onclick=run(()=>nativeCommand('light',id,{}));maskActions.append(b);}masks.insertBefore(maskActions,masks.lastChild);
  const brushMore=document.createElement('details');brushMore.className='develop-section native-brush-settings';brushMore.innerHTML='<summary>Penselförinställningar och dynamik</summary><select aria-label="Penselförinställning"><option value="">Välj originalpensel…</option></select><button type="button">Läs penselförinställningar</button>';
  const preset=brushMore.querySelector('select');brushMore.querySelector('button').onclick=run(async()=>{const result=await nativeCommand('photo','brush.presets.list',{});preset.replaceChildren(new Option('Välj originalpensel…',''));for(const p of result.presets)preset.append(new Option(p.name,p.name));});preset.onchange=run(async()=>{if(preset.value){await nativeCommand('photo','tools.setBrush',{preset:preset.value});const brush=getState().project.workspace.photo_tools.brush;$('brush-size').value=brush.size;$('brush-hardness').value=Math.round(brush.hardness*100);$('brush-opacity').value=Math.round(brush.opacity*100);$('brush-flow').value=Math.round(brush.flow*100);selectTool('brush');}});
  for(const [label,key]of [['Formdynamik','shapeDynamics'],['Spridning','scattering'],['Färgdynamik','colorDynamics'],['Textur','texture'],['Överföring','transfer']]){const row=document.createElement('label');row.className='field';const input=document.createElement('input');input.type='checkbox';input.onchange=run(()=>nativeCommand('photo','tools.setBrush',{[key]:{enabled:input.checked}}));row.append(label,input);brushMore.append(row);}const settingsLink=document.createElement('button');settingsLink.textContent='Alla penselinställningar…';settingsLink.onclick=()=>open('photo','brush');brushMore.append(settingsLink);$('photo-panel').append(brushMore);
  masks.querySelector('#local-exposure').onchange=run(async e=>{await nativeCommand('light','mask.adjust',{values:{exposure:Number(e.target.value)}});});
  const filmTools=document.createElement('section');filmTools.className='panel-section native-film-tools';filmTools.innerHTML='<h3>Spår och effekter</h3><div class="native-film-actions"></div><div class="native-track-list"></div><button class="full-button">Alla FilmCraft-verktyg…</button>';$('film-panel').append(filmTools);filmTools.lastChild.onclick=()=>open('film');
  for(const [label,id,params]of [['+ Videospår','sequence.addTracks',{video:1,audio:0}],['+ Ljudspår','sequence.addTracks',{video:0,audio:1}],['Övergång','sequence.applyVideoTransition',{effect:'cross_dissolve',frames:12}],['Effekter…',null,null]]){const b=document.createElement('button');b.textContent=label;b.onclick=run(()=>id?nativeCommand('film',id,params):open('film','','Effects'));filmTools.querySelector('.native-film-actions').append(b);}
  const properties=document.createElement('div');properties.className='native-layer-properties';nativeLayers.insertBefore(properties,nativeLayers.lastChild);
  function showLayerProperties(l){properties.replaceChildren();const title=document.createElement('input');title.type='text';title.value=l.name;title.setAttribute('aria-label','Objektnamn');title.onchange=run(()=>nativeCommand('photo','layer.setProps',{layer:'@'+l.id,name:title.value}));properties.append(title);const opacity=document.createElement('input');opacity.type='range';opacity.min=0;opacity.max=100;opacity.value=Math.round(l.opacity*100);opacity.setAttribute('aria-label','Objektopacitet');opacity.onchange=run(()=>nativeCommand('photo','layer.setProps',{layer:'@'+l.id,opacity:Number(opacity.value)/100}));const blend=document.createElement('select');blend.setAttribute('aria-label','Objektets blandningsläge');for(const b of getState().blend_modes)blend.append(new Option(b.label,b.id));blend.value=getState().blend_modes.find(b=>b.id===l.blend||b.label===l.blend)?.id||'Normal';blend.onchange=run(()=>nativeCommand('photo','layer.setProps',{layer:'@'+l.id,blend:blend.value}));properties.append(opacity,blend);for(const [label,id,params]of [['Duplicera','layer.duplicate',{layer:'@'+l.id,inPlace:true}],[l.hasMask?'Redigera mask':'Lägg till mask','layer.layerMask.revealAll',{layer:'@'+l.id}],['Ta bort','layer.delete',{layer:'@'+l.id}]]){const b=document.createElement('button');b.textContent=label;b.onclick=run(async()=>{if(id==='layer.layerMask.revealAll'){if(!l.hasMask)await nativeCommand('photo',id,params);maskTarget=l.id;selectTool('brush');status('Lagermask vald · måla svart för att dölja, vitt för att visa');}else await nativeCommand('photo',id,params);});properties.append(b);}const pixels=document.createElement('button');pixels.textContent='Redigera bildinnehåll';pixels.onclick=()=>{maskTarget=null;selectTool('brush');status('Bildinnehåll valt');};properties.append(pixels);}
  // Split a JSON-ish signature only at its top-level separators.
  function splitSignature(text){let depth=0,quote=false,begin=0,out=[];for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&text[i-1]!=='\\')quote=!quote;if(quote)continue;if('([{'.includes(c))depth++;else if(')]}'.includes(c))depth--;else if(c===','&&depth===0){out.push(text.slice(begin,i));begin=i+1;}}out.push(text.slice(begin));return out;}
  function schema(signature){const begin=signature.indexOf('{');if(begin<0)return [];let depth=0,end=signature.length;for(let i=begin;i<signature.length;i++){if(signature[i]==='{')depth++;if(signature[i]==='}'&&!--depth){end=i;break;}}return splitSignature(signature.slice(begin+1,end)).map(part=>{const m=part.trim().match(/^"?([\w.-]+)"?(\??)\s*:\s*(.+)$/);return m?{key:m[1],optional:!!m[2]||m[3].includes('?'),type:m[3]}:null;}).filter(Boolean);}
  function field(spec){const row=document.createElement('label');row.className='field native-param';const title=document.createElement('span');title.textContent=spec.key.replace(/([a-z])([A-Z])/g,'$1 $2');row.append(title);let input;const type=spec.type,range=type.match(/(-?\d+(?:\.\d+)?)\.\.(-?\d+(?:\.\d+)?)/),quoted=type.match(/^"([^"=]+)"(?:\s*=|\s*\?\s*=|\s*$)/),options=quoted?.[1].split('|').filter(x=>x&&!x.includes('…'));
    const def=type.match(/=\s*("[^"]*"|-?\d+(?:\.\d+)?|true|false)/)?.[1];
    if(engine==='photo'&&['layer','sourceLayer','parent'].includes(spec.key)){input=document.createElement('select');input.append(new Option('Aktuellt lager',''));const visit=layers=>{for(const l of layers||[]){input.append(new Option(l.name,'@'+l.id));visit(l.children);}};visit(currentView?.layers);if(getState()?.project.workspace.native_target)input.value='@'+getState().project.workspace.native_target;}
    else if(options?.length>1){input=document.createElement('select');for(const value of options)input.append(new Option(value,value));if(def)input.value=def.replaceAll('"','');}
    else if(type.startsWith('bool')){input=document.createElement('input');input.type='checkbox';input.checked=def==='true';}
    else if(range||/^number|^f64|^i64|^u32|^n\b|^percent|^px\b|^ticks|^id\??$|^itemId|^binId/.test(type)){input=document.createElement('input');input.type='number';input.step='any';if(range){input.min=range[1];input.max=range[2];}input.value=def??(range?Math.max(Number(range[1]),Math.min(Number(range[2]),0)):0);}
    else if(type.startsWith('[')||type.startsWith('{')||type.includes(' JSON')||/^any\b|^ParamValue/.test(type)){input=document.createElement('textarea');input.rows=2;input.placeholder=type.startsWith('{')?'{}':'[]';input.dataset.json='true';}
    else{input=document.createElement('input');input.type='text';input.value=def?.replaceAll('"','')||'';if(spec.key==='clip'&&engine==='film')input.value=getState()?.active_clip?.id?.slice(5)||'';if(spec.key==='id'&&engine==='light')input.value=getState()?.project.workspace.active_mask??'';}
    if(engine==='film'&&spec.key==='clip'&&input.type==='number')input.value=getState()?.active_clip?.id?.slice(5)||0;input.name=spec.key;input.title=type;row.append(input);if(spec.optional){row.classList.add('optional-param');const use=document.createElement('input');use.type='checkbox';use.className='use-param';use.setAttribute('aria-label','Använd '+spec.key);use.checked=!!def;row.prepend(use);}return row;
  }
  function select(c){selected=c;form.querySelector('h3').textContent=c.label;fields.replaceChildren(...schema(c.params).map(field));form.querySelector('.native-command-note').textContent=c.connected?'': 'Den här funktionen behöver en webbadapter för filer, enheter eller modeller.';apply.disabled=!c.connected;apply.textContent=c.journal?'Använd på vald omfattning':'Visa';sync();}
  function refreshList(){if(!catalog)return;list.replaceChildren();const q=search.value.toLowerCase();for(const c of catalog[engine]){if(category.value&&!c.menu.includes(category.value))continue;if(q&&!`${c.label} ${c.id} ${c.menu.join(' ')}`.toLowerCase().includes(q))continue;const b=document.createElement('button');b.className='native-command'+(!c.connected?' unavailable':'');const label=document.createElement('span');label.textContent=c.label;const path=document.createElement('small');path.textContent=c.menu.join(' › ')||c.id;b.append(label,path);b.onclick=()=>select(c);list.append(b);}if(!list.childNodes.length)list.textContent='Inga verktyg hittades.';}
  function setEngine(value){engine=value;area.value=value;category.replaceChildren(new Option('Alla kategorier',''));for(const name of [...new Set(catalog?.[engine].flatMap(c=>c.menu.slice(0,1)))].sort())category.append(new Option(name,name));selected=null;refreshList();}
  async function open(value='photo',q='',cat=''){if(!catalog)catalog=await rpc('catalog');setEngine(value);search.value=q;category.value=cat;refreshList();if(!dialog.open)dialog.showModal();search.focus();}
  area.onchange=()=>setEngine(area.value);search.oninput=refreshList;category.onchange=refreshList;
  form.onsubmit=run(async e=>{e.preventDefault();if(!selected?.connected)return;const params={};for(const row of fields.children){const input=row.querySelector('[name]');if(row.classList.contains('optional-param')&&!row.querySelector('.use-param').checked)continue;if(!input.value&&input.type!=='checkbox')continue;params[input.name]=input.dataset.json?JSON.parse(input.value):input.type==='checkbox'?input.checked:input.type==='number'?Number(input.value):input.value;}const c=selected;const result=await nativeCommand(engine,c.id,params);status(c.label+' · vald omfattning');if(!c.journal){let out=form.querySelector('.native-query-result');if(!out){out=document.createElement('pre');out.className='native-query-result';form.append(out);}out.textContent=JSON.stringify(result,null,2);}else dialog.close();});
  document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();open(getState()?.project.workspace.mode||'photo');}});
  async function refreshLayers(){const p=getState()?.project;if(!p?.clips.length||!getState().active_clip)return;const token=++layerToken;const view=await nativeView();if(token!==layerToken)return;currentView=view;const root=nativeLayers.querySelector('.native-layer-list');root.replaceChildren();function render(layers,depth=0){for(const l of layers){const row=document.createElement('button');row.className='native-layer'+(l.id===p.workspace.native_target?' active':'');row.style.paddingLeft=(8+depth*12)+'px';if(p.layers.some(x=>x.id===l.id)){if(l.children)render(l.children,depth+1);continue;}const eye=document.createElement('span');eye.textContent=l.visible?'◉':'○';eye.title='Visa / dölj';eye.onclick=run(async e=>{e.stopPropagation();await nativeCommand('photo','layer.setProps',{layer:'@'+l.id,visible:!l.visible});});const name=document.createElement('span');name.textContent=l.name;row.append(eye,name);row.onclick=run(async()=>{await command('view.set',{native_target:l.id},false);showLayerProperties(l);});root.append(row);if(l.children)render(l.children,depth+1);}}render(view.layers);
    drawSelection();return view;}
  function drawSelection(){const view=currentView;if(!getState()?.project.workspace.photo_selection?.length)return;if(view?.selectionOutline?.length){const c=$('stroke-preview');overlay.clearRect(0,0,c.width,c.height);overlay.strokeStyle='white';overlay.lineWidth=1;overlay.setLineDash([4,3]);overlay.beginPath();for(const [a,b]of view.selectionOutline){overlay.moveTo(a[0]*c.width,a[1]*c.height);overlay.lineTo(b[0]*c.width,b[1]*c.height);}overlay.stroke();overlay.setLineDash([]);}}
  function sync(){const s=getState();if(!s)return;const p=s.project,w=p.workspace;effectsUI.sync();form.querySelector('.native-command-scope').textContent=engine==='film'?'Projektets tidslinje · klippverktyg påverkar hela det valda klippet':$('scope-description').textContent;const settings=s.look?.settings,maskList=masks.querySelector('.local-mask-list');maskList.replaceChildren();for(const m of settings?.masks||[]){const b=document.createElement('button');b.textContent=m.name||'Mask '+m.id;b.classList.toggle('active',m.id===w.active_mask);b.onclick=run(()=>nativeCommand('light','mask.select',{id:m.id}));maskList.append(b);}const active=settings?.masks?.find(m=>m.id===w.active_mask);masks.querySelector('#local-exposure').disabled=!active;masks.querySelector('#local-exposure').value=active?.adjust?.exposure??0;masks.querySelector('output').textContent=masks.querySelector('#local-exposure').value;for(const input of masks.querySelectorAll('[data-local]')){input.disabled=!active;input.value=active?.adjust?.[input.dataset.local]??(input.dataset.local==='amount'?100:0);input.nextSibling.textContent=input.value;}for(const b of masks.querySelectorAll('[data-mask-action]'))b.disabled=!active;
    const tracks=filmTools.querySelector('.native-track-list');tracks.replaceChildren();for(const t of [...(p.timeline?.video_tracks||[]),...(p.timeline?.audio_tracks||[])]){const row=document.createElement('div');row.className='native-track';const name=document.createElement('span');name.textContent=t.name;const toggle=document.createElement('button');toggle.textContent=t.enabled&&!t.muted?'◉':'○';toggle.title='Aktivera / stäng av spår';toggle.onclick=run(()=>nativeCommand('film','timeline.setTrack',{track:t.id,enabled:!t.enabled,muted:t.kind==='Audio'?!t.muted:undefined}));row.append(name,toggle);tracks.append(row);}
    if(!isPlaying()){const sig=JSON.stringify([p.photo_operations,w.playhead,w.native_target,w.photo_selection,p.layers,p.adjustments,p.project_look,p.timeline,p.assets]);if(sig!==viewSignature){viewSignature=sig;refreshLayers().catch(e=>status(e.message,true));}}
  }
  function xy(pt){const p=getState().project;return [pt[0]*p.width,pt[1]*p.height];}
  async function start(id,pt,e){if(!tools[id])return;if((id==='clone'||id==='heal')&&e.altKey){[cloneSource]=await canvasCoordinates([pt]);status('Klonkälla vald');return;}if(['clone','heal'].includes(id)&&!cloneSource)throw new Error('Alt-klicka på canvasen för att välja en källa först');gesture={id,points:[pt],scope:editScope()};canvas.setPointerCapture(e.pointerId);}
  function move(pt){if(!gesture)return;gesture.points.push(pt);const c=$('stroke-preview');overlay.clearRect(0,0,c.width,c.height);overlay.strokeStyle=$('color').value;overlay.lineWidth=2;overlay.beginPath();gesture.points.forEach((p,i)=>i?overlay.lineTo(p[0]*c.width,p[1]*c.height):overlay.moveTo(p[0]*c.width,p[1]*c.height));overlay.stroke();}
  async function end(){const g=gesture;gesture=null;if(!g)return;overlay.clearRect(0,0,$('stroke-preview').width,$('stroke-preview').height);const [name,eng,cmd]=tools[g.id],mapped=await canvasCoordinates(g.points,eng),pts=mapped.map((p,i)=>[...p,g.points[i][2]]),pixels=pts,a=pts[0],b=pts.at(-1),from=a.slice(0,2),to=b.slice(0,2),size=Number($('brush-size').value),color=$('color').value;let params={};
    if(g.id==='lasso')params={points:pixels.map(p=>p.slice(0,2))};else if(['wand','bucket','magicErase'].includes(g.id))params={x:from[0],y:from[1],color,sampleAllLayers:true};
    else if(g.id==='gradient')params={from,to,colors:[color,'#ffffff']};
    else if(['rectangle','ellipse','line','pen'].includes(g.id)){params={kind:g.id==='rectangle'?'rect':g.id==='pen'?'path':g.id,fill:color,rect:[Math.min(from[0],to[0]),Math.min(from[1],to[1]),Math.max(1,Math.abs(to[0]-from[0])),Math.max(1,Math.abs(to[1]-from[1]))],from,to,weight:size};if(g.id==='pen')params.path={subpaths:[{closed:true,knots:pixels.map(p=>p.slice(0,2))}]};}
    else if(g.id==='maskLinear')params={kind:'linear',start:a.slice(0,2),end:b.slice(0,2)};
    else if(g.id==='maskRadial')params={kind:'radial',center:[(a[0]+b[0])/2,(a[1]+b[1])/2],rx:Math.max(.001,Math.abs(a[0]-b[0])/2),ry:Math.max(.001,Math.abs(a[1]-b[1])/2)};
    else if(g.id==='maskBrush'){if(getState().project.workspace.active_mask==null)await nativeCommand('light','mask.add',{kind:'brush'},g.scope);params={points:pts.map(p=>p.slice(0,2)),size:size/Math.max(getState().project.width,getState().project.height)};}
    else if(g.id==='remove')params={mode:'heal',points:pts.map(p=>p.slice(0,2)),size:size/Math.max(getState().project.width,getState().project.height)};
    else if(g.id==='redEye')params={center:a.slice(0,2),rx:size/getState().project.width,ry:size/getState().project.height};
    else if(g.id==='crop')params={rect:[Math.min(a[0],b[0]),Math.min(a[1],b[1]),Math.max(a[0],b[0]),Math.max(a[1],b[1])]};
    else {params={points:pixels,size,color};if(['clone','heal'].includes(g.id))params.source=cloneSource;if(!['pencil','mixer','replaceColor','backgroundErase'].includes(g.id)){params.hardness=Number($('brush-hardness').value);params.opacity=Math.max(1,Number($('brush-opacity').value));params.flow=Math.max(1,Number($('brush-flow').value));}else if(g.id==='pencil')params.opacity=Number($('brush-opacity').value)/100;else if(g.id==='mixer')params.flow=Number($('brush-flow').value);else if(g.id==='backgroundErase')params.hardness=Number($('brush-hardness').value)/100;}
    if(eng==='photo'&&cmd.startsWith('paint.')&&!['paint.mixerBrush','paint.colorReplacement','paint.backgroundEraser','paint.magicEraser'].includes(cmd))params.target=paintTarget();await nativeCommand(eng,cmd,params,g.scope);status(name+' · vald omfattning');
  }
  function paintTarget(){const w=getState()?.project.workspace;return maskTarget&&(w?.native_target||w?.selected_layer)===maskTarget?'mask':'pixels';}
  return {open,sync,refreshLayers,drawSelection,paintTarget,start,move,end,toolName:id=>tools[id]?.[0],catalog:()=>catalog,tools};
}
